### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mattbuske** [mattbuske/pcg-bunny#24]
## v1.2.0
- [X] Recreate application in C#
- [X] Implement MkDocs Standard structure
- [X] Restructure repository based on language
- [ ] Update documentation to include C# information
- [X] Add Dependabot to Github Actions

## v1.3.0
- [ ] Add Java version of the application
